class AuctionsModel {
  String? text;
  String? status;
  double? price1;
  double? price2;
  String? image;
  String? brand;
  String? model;
  String? referance;
  int? year;
  double? size;
  String? dialColor;
  String? caseMaterial;
  String? condition;
  String? fullSet;
  double? askingPrice;
  String? lastBidder;
  double? numberOfBidders;
  String? date;
  String? igAccount;
  String? country;

  AuctionsModel({
    this.text,
    this.price1,
    this.price2,
    this.status,
    this.size,
    this.date,
    this.image,
    this.brand,
    this.caseMaterial,
    this.condition,
    this.country,
    this.dialColor,
    this.fullSet,
    this.igAccount,
    this.askingPrice,
    this.lastBidder,
    this.model,
    this.numberOfBidders,
    this.referance,
    this.year,
  });
}

List<AuctionsModel> AuctionsList = [
  AuctionsModel(
    text:
        "Vacheron constantin overseas chronograph steel 42.5mm blue dial 2021 unworn, kuwait",
    price1: 3500,
    price2: 4000,
    status: "Sold",
    image: "assets/images/watch.png",
    brand: "Vacheron Costantine",
    caseMaterial: "Steel",
    condition: "Unworn",
    country: "Kuwait",
    date: "8 august 2022",
    dialColor: "Blue Dial",
    fullSet: "Full Set",
    igAccount: "elite_watches_q8",
    askingPrice: 0,
    lastBidder: "khal9ne",
    model: "Overseas Chronograph",
    numberOfBidders: 2,
    referance: "5500V/110A-B148",
    size: 42.5,
    year: 2021,
  ),
  AuctionsModel(
    text:
        "Vacheron constantin overseas chronograph steel 42.5mm blue dial 2021 unworn, kuwait",
    price1: 3500,
    price2: 4000,
    status: "Sold",
    image: "assets/images/watch2.jpg",
    brand: "Vacheron Costantine",
    caseMaterial: "Steel",
    condition: "Unworn",
    country: "Kuwait",
    date: "8 august 2022",
    dialColor: "Blue Dial",
    fullSet: "Full Set",
    igAccount: "elite_watches_q8",
    askingPrice: 0,
    lastBidder: "khal9ne",
    model: "Overseas Chronograph",
    numberOfBidders: 2,
    referance: "5500V/110A-B148",
    size: 42.5,
    year: 2021,
  ),
  AuctionsModel(
    text:
        "Vacheron constantin overseas chronograph steel 42.5mm blue dial 2021 unworn, kuwait",
    price1: 3500,
    price2: 4000,
    status: "Sold",
    image: "assets/images/watch5.jpg",
    brand: "Vacheron Costantine",
    caseMaterial: "Steel",
    condition: "Unworn",
    country: "Kuwait",
    date: "8 august 2022",
    dialColor: "Blue Dial",
    fullSet: "Full Set",
    igAccount: "elite_watches_q8",
    askingPrice: 0,
    lastBidder: "khal9ne",
    model: "Overseas Chronograph",
    numberOfBidders: 2,
    referance: "5500V/110A-B148",
    size: 42.5,
    year: 2021,
  ),
  AuctionsModel(
    text:
        "Vacheron constantin overseas chronograph steel 42.5mm blue dial 2021 unworn, kuwait",
    price1: 3500,
    price2: 4000,
    status: "Sold",
    image: "assets/images/watch3.jpg",
    brand: "Vacheron Costantine",
    caseMaterial: "Steel",
    condition: "Unworn",
    country: "Kuwait",
    date: "8 august 2022",
    dialColor: "Blue Dial",
    fullSet: "Full Set",
    igAccount: "elite_watches_q8",
    askingPrice: 0,
    lastBidder: "khal9ne",
    model: "Overseas Chronograph",
    numberOfBidders: 2,
    referance: "5500V/110A-B148",
    size: 42.5,
    year: 2021,
  ),
  AuctionsModel(
    text:
        "Vacheron constantin overseas chronograph steel 42.5mm blue dial 2021 unworn, kuwait",
    price1: 3500,
    price2: 4000,
    status: "Sold",
    image: "assets/images/watch.png",
    brand: "Vacheron Costantine",
    caseMaterial: "Steel",
    condition: "Unworn",
    country: "Kuwait",
    date: "8 august 2022",
    dialColor: "Blue Dial",
    fullSet: "Full Set",
    igAccount: "elite_watches_q8",
    askingPrice: 0,
    lastBidder: "khal9ne",
    model: "Overseas Chronograph",
    numberOfBidders: 2,
    referance: "5500V/110A-B148",
    size: 42.5,
    year: 2021,
  ),
  AuctionsModel(
    text:
        "Vacheron constantin overseas chronograph steel 42.5mm blue dial 2021 unworn, kuwait",
    price1: 3500,
    price2: 4000,
    status: "Sold",
    image: "assets/images/img.png",
    brand: "Vacheron Costantine",
    caseMaterial: "Steel",
    condition: "Unworn",
    country: "Kuwait",
    date: "8 august 2022",
    dialColor: "Blue Dial",
    fullSet: "Full Set",
    igAccount: "elite_watches_q8",
    askingPrice: 0,
    lastBidder: "khal9ne",
    model: "Overseas Chronograph",
    numberOfBidders: 2,
    referance: "5500V/110A-B148",
    size: 42.5,
    year: 2021,
  ),
  AuctionsModel(
    text:
        "Vacheron constantin overseas chronograph steel 42.5mm blue dial 2021 unworn, kuwait",
    price1: 3500,
    price2: 4000,
    status: "Sold",
    image: "assets/images/img.png",
    brand: "Vacheron Costantine",
    caseMaterial: "Steel",
    condition: "Unworn",
    country: "Kuwait",
    date: "8 august 2022",
    dialColor: "Blue Dial",
    fullSet: "Full Set",
    igAccount: "elite_watches_q8",
    askingPrice: 0,
    lastBidder: "khal9ne",
    model: "Overseas Chronograph",
    numberOfBidders: 2,
    referance: "5500V/110A-B148",
    size: 42.5,
    year: 2021,
  ),
  AuctionsModel(
    text:
        "Vacheron constantin overseas chronograph steel 42.5mm blue dial 2021 unworn, kuwait",
    price1: 3500,
    price2: 4000,
    status: "Sold",
    image: "assets/images/img.png",
    brand: "Vacheron Costantine",
    caseMaterial: "Steel",
    condition: "Unworn",
    country: "Kuwait",
    date: "8 august 2022",
    dialColor: "Blue Dial",
    fullSet: "Full Set",
    igAccount: "elite_watches_q8",
    askingPrice: 0,
    lastBidder: "khal9ne",
    model: "Overseas Chronograph",
    numberOfBidders: 2,
    referance: "5500V/110A-B148",
    size: 42.5,
    year: 2021,
  ),
  AuctionsModel(
    text:
        "Vacheron constantin overseas chronograph steel 42.5mm blue dial 2021 unworn, kuwait",
    price1: 3500,
    price2: 4000,
    status: "Sold",
    image: "assets/images/img.png",
    brand: "Vacheron Costantine",
    caseMaterial: "Steel",
    condition: "Unworn",
    country: "Kuwait",
    date: "8 august 2022",
    dialColor: "Blue Dial",
    fullSet: "Full Set",
    igAccount: "elite_watches_q8",
    askingPrice: 0,
    lastBidder: "khal9ne",
    model: "Overseas Chronograph",
    numberOfBidders: 2,
    referance: "5500V/110A-B148",
    size: 42.5,
    year: 2021,
  ),
  AuctionsModel(
    text:
        "Vacheron constantin overseas chronograph steel 42.5mm blue dial 2021 unworn, kuwait",
    price1: 3500,
    price2: 4000,
    status: "Sold",
    image: "assets/images/img.png",
    brand: "Vacheron Costantine",
    caseMaterial: "Steel",
    condition: "Unworn",
    country: "Kuwait",
    date: "8 august 2022",
    dialColor: "Blue Dial",
    fullSet: "Full Set",
    igAccount: "elite_watches_q8",
    askingPrice: 0,
    lastBidder: "khal9ne",
    model: "Overseas Chronograph",
    numberOfBidders: 2,
    referance: "5500V/110A-B148",
    size: 42.5,
    year: 2021,
  ),
  AuctionsModel(
    text:
        "Vacheron constantin overseas chronograph steel 42.5mm blue dial 2021 unworn, kuwait",
    price1: 3500,
    price2: 4000,
    status: "Sold",
    image: "assets/images/img.png",
    brand: "Vacheron Costantine",
    caseMaterial: "Steel",
    condition: "Unworn",
    country: "Kuwait",
    date: "8 august 2022",
    dialColor: "Blue Dial",
    fullSet: "Full Set",
    igAccount: "elite_watches_q8",
    askingPrice: 0,
    lastBidder: "khal9ne",
    model: "Overseas Chronograph",
    numberOfBidders: 2,
    referance: "5500V/110A-B148",
    size: 42.5,
    year: 2021,
  ),
  AuctionsModel(
    text:
        "Vacheron constantin overseas chronograph steel 42.5mm blue dial 2021 unworn, kuwait",
    price1: 3500,
    price2: 4000,
    status: "Sold",
    image: "assets/images/img.png",
    brand: "Vacheron Costantine",
    caseMaterial: "Steel",
    condition: "Unworn",
    country: "Kuwait",
    date: "8 august 2022",
    dialColor: "Blue Dial",
    fullSet: "Full Set",
    igAccount: "elite_watches_q8",
    askingPrice: 0,
    lastBidder: "khal9ne",
    model: "Overseas Chronograph",
    numberOfBidders: 2,
    referance: "5500V/110A-B148",
    size: 42.5,
    year: 2021,
  ),
];
